name: tkChat
version: '${version}'
main: dev.tkkr.tkchat.paper.TkChatPaperPlugin
description: Paper backend bridge for tkChat
api-version: '${apiVersion}'
authors: [tkkr]
dependencies:
  server:
    SignedVelocity:
      load: BEFORE
      required: false
      join-classpath: false
